### ISSUE TITLE
Missing argument in driver

### ISSUE THREAD

**Issue by Werner-G** [mpi3d/robotic-arm-control#2]
I'm trying to get it worked, but something is wrong:

>  >>> %Run -c $EDITOR_CONTENT
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "robotic_arm.py", line 10, in <module>
  File "robotic_arm.py", line 39, in OneMotor
TypeError: function takes 2 positional arguments but 1 were given

I copied and pasted the example.

**Comment by mpi3d** [comment]
Which line did you execute?

**Comment by Werner-G** [comment]
I just executed the example.py, and I showed the error log from THONNY. But the mistake is probably the wrong driver: I cannot find the Adafruit_PCA9685.py, just an generic PCA9685.py. Can you please publish your driver?

**Comment by mpi3d** [comment]
I think it's this one: https://github.com/adafruit/Adafruit_CircuitPython_PCA9685

**Comment by Werner-G** [comment]
Oh, this is Circuit Python, not Micropython. I have no idea how to use this driver. Any chance to rework your control to Micropython using a 'standard' driver like 
https://github.com/adafruit/micropython-adafruit-pca9685/blob/master/pca9685.py

Thank you!

**Comment by mpi3d** [comment]
This driver is depreciated. You should use the Circuit Python one instead. It should work on a normal Python too.

**Comment by Werner-G** [comment]
No, it cannot, see the preamble of the 'adafruit_pca9685.py'-driver: :
```
from adafruit_register.i2c_struct import UnaryStruct
from adafruit_register.i2c_struct_array import StructArray
from adafruit_bus_device import i2c_device
```
Maybe your driver only work with a RasPi, and not with ESP32? Please doublecheck your driver, I really need this for my robotic arm.

**Comment by mpi3d** [comment]
I see. Unfortunately, I don't have time to implement this. You will have to do it yourself. The driver shouldn't be much different from the actual one. Feel free to make a pull request.
